apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: bigbang
  namespace: bigbang
spec:
  interval: 1m
  url: https://github.com/branflaker/test-bigbang
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bigbang
  namespace: bigbang
spec:
  interval: 1m
  path: "./base"
  prune: true
  sourceRef:
    kind: GitRepository
    name: bigbang
  targetNamespace: bigbang
  timeout: 5m
