domain: bigbang.dev
flux:
  enabled: true

# Configure gateways to use NodePort instead of LoadBalancer for k3d compatibility
istioGateway:
  values:
    gateways:
      public:
        service:
          type: NodePort
      passthrough:
        service:
          type: NodePort

